import { Employee, Task, Message, Meeting, Evaluation, Attendance } from '@/types';

export const mockEmployees: Employee[] = [
  {
    id: 'emp-001',
    name: 'John Smith',
    email: 'john.smith@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=john',
    department: 'Engineering',
    position: 'Senior Developer',
    role: 'employee',
    joinDate: '2023-01-15',
    status: 'active',
    performanceScore: 4.5,
  },
  {
    id: 'emp-002',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    department: 'Marketing',
    position: 'Marketing Manager',
    role: 'employee',
    joinDate: '2023-02-20',
    status: 'active',
    performanceScore: 4.8,
  },
  {
    id: 'emp-003',
    name: 'Michael Brown',
    email: 'michael.brown@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=michael',
    department: 'Sales',
    position: 'Sales Executive',
    role: 'employee',
    joinDate: '2023-03-10',
    status: 'active',
    performanceScore: 4.2,
  },
  {
    id: 'emp-004',
    name: 'Emily Davis',
    email: 'emily.davis@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emily',
    department: 'HR',
    position: 'HR Specialist',
    role: 'employee',
    joinDate: '2023-04-05',
    status: 'active',
    performanceScore: 4.6,
  },
  {
    id: 'emp-005',
    name: 'David Wilson',
    email: 'david.wilson@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    department: 'Engineering',
    position: 'Frontend Developer',
    role: 'employee',
    joinDate: '2023-05-12',
    status: 'active',
    performanceScore: 4.4,
  },
  {
    id: 'emp-006',
    name: 'Lisa Anderson',
    email: 'lisa.anderson@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisa',
    department: 'Marketing',
    position: 'Content Writer',
    role: 'employee',
    joinDate: '2023-06-18',
    status: 'active',
    performanceScore: 4.3,
  },
  {
    id: 'emp-007',
    name: 'Robert Taylor',
    email: 'robert.taylor@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=robert',
    department: 'Sales',
    position: 'Sales Manager',
    role: 'employee',
    joinDate: '2023-07-22',
    status: 'active',
    performanceScore: 4.7,
  },
  {
    id: 'emp-008',
    name: 'Jennifer Martinez',
    email: 'jennifer.martinez@company.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jennifer',
    department: 'Engineering',
    position: 'Backend Developer',
    role: 'employee',
    joinDate: '2023-08-30',
    status: 'on-leave',
    performanceScore: 4.1,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    title: 'Complete Q1 Report',
    description: 'Prepare quarterly performance report with analytics and insights',
    assignedTo: 'emp-001',
    assignedBy: 'admin-001',
    status: 'in-progress',
    priority: 'high',
    deadline: '2024-03-31',
    createdAt: '2024-03-01',
  },
  {
    id: 'task-002',
    title: 'Update Marketing Strategy',
    description: 'Review and update marketing strategy for Q2 2024',
    assignedTo: 'emp-002',
    assignedBy: 'admin-001',
    status: 'completed',
    priority: 'medium',
    deadline: '2024-03-25',
    createdAt: '2024-03-05',
    completedAt: '2024-03-20',
  },
  {
    id: 'task-003',
    title: 'Client Presentation',
    description: 'Prepare and deliver sales presentation to new client',
    assignedTo: 'emp-003',
    assignedBy: 'admin-001',
    status: 'in-progress',
    priority: 'high',
    deadline: '2024-04-05',
    createdAt: '2024-03-15',
  },
  {
    id: 'task-004',
    title: 'Employee Onboarding',
    description: 'Complete onboarding process for 3 new hires',
    assignedTo: 'emp-004',
    assignedBy: 'admin-001',
    status: 'completed',
    priority: 'medium',
    deadline: '2024-03-28',
    createdAt: '2024-03-10',
    completedAt: '2024-03-27',
  },
  {
    id: 'task-005',
    title: 'Website Redesign',
    description: 'Implement new UI/UX design for company website',
    assignedTo: 'emp-005',
    assignedBy: 'admin-001',
    status: 'in-progress',
    priority: 'high',
    deadline: '2024-04-15',
    createdAt: '2024-03-08',
  },
  {
    id: 'task-006',
    title: 'Content Calendar',
    description: 'Create content calendar for social media Q2',
    assignedTo: 'emp-006',
    assignedBy: 'admin-001',
    status: 'pending',
    priority: 'medium',
    deadline: '2024-04-01',
    createdAt: '2024-03-20',
  },
  {
    id: 'task-007',
    title: 'Sales Training',
    description: 'Conduct sales training workshop for team',
    assignedTo: 'emp-007',
    assignedBy: 'admin-001',
    status: 'completed',
    priority: 'medium',
    deadline: '2024-03-22',
    createdAt: '2024-03-05',
    completedAt: '2024-03-21',
  },
  {
    id: 'task-008',
    title: 'API Development',
    description: 'Develop RESTful API for mobile application',
    assignedTo: 'emp-008',
    assignedBy: 'admin-001',
    status: 'pending',
    priority: 'high',
    deadline: '2024-04-20',
    createdAt: '2024-03-18',
  },
  {
    id: 'task-009',
    title: 'Database Optimization',
    description: 'Optimize database queries and improve performance',
    assignedTo: 'emp-001',
    assignedBy: 'admin-001',
    status: 'pending',
    priority: 'medium',
    deadline: '2024-04-10',
    createdAt: '2024-03-22',
  },
  {
    id: 'task-010',
    title: 'Email Campaign',
    description: 'Design and launch email marketing campaign',
    assignedTo: 'emp-002',
    assignedBy: 'admin-001',
    status: 'in-progress',
    priority: 'medium',
    deadline: '2024-04-08',
    createdAt: '2024-03-25',
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-001',
    from: 'admin-001',
    to: 'all',
    subject: 'Company Meeting Tomorrow',
    content: 'Reminder: All hands meeting tomorrow at 10 AM',
    timestamp: new Date().toISOString(),
    read: false,
    type: 'broadcast',
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: 'meet-001',
    title: 'Weekly Team Sync',
    description: 'Weekly team synchronization meeting',
    scheduledBy: 'admin-001',
    attendees: ['emp-001', 'emp-002', 'emp-003'],
    date: '2024-03-28',
    time: '10:00',
    link: 'https://meet.google.com/abc-defg-hij',
    status: 'scheduled',
  },
];

export const mockEvaluations: Evaluation[] = [
  {
    id: 'eval-001',
    employeeId: 'emp-001',
    evaluatedBy: 'admin-001',
    score: 4.5,
    date: '2024-03-15',
    comments: 'Excellent performance this quarter',
    categories: {
      productivity: 4.5,
      quality: 4.8,
      teamwork: 4.3,
      communication: 4.5,
    },
  },
];

export const mockAttendance: Attendance[] = [
  {
    id: 'att-001',
    employeeId: 'emp-001',
    date: new Date().toISOString().split('T')[0],
    checkIn: '09:00',
    status: 'present',
  },
];
